title: Site title
description: Description of site
theme: jekyll-theme-architect

collections:
  assignments:
    output: true
  something:
    output: true

defaults:
  - scope:
      path: "assignments"
      type: "assignments"
    values:
      layout: "assignments"
  - scope:
      path: "something"
      type: "something"
    values:
      layout: "something"
